version: '3'
services:
  web:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html
  app:
    # image: php:7.4.7-fpm-alpine
    build: ./app
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./data/html:/var/www/html
  db:
    image: mariadb:latest
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
